name: tiny-transformer
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1
  - numpy
  - tqdm
  - pip
  - pip:
      - pre-commit>=3.7.0,<4
      - transformers>=4.51.0,<5
      - datasets>=2.20.0,<5
      - accelerate>=0.33.0,<2
